version: "3.1"

services:
  db:
    container_name: SCRIM_POSTGRES
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    volumes:
      - ../data:/var/lib/postgresql/data/

  api:
    container_name: SCRIM_API
    build: .
    command: npm start
    ports:
      - ${API_PORT}:3000
    volumes:
      - .:/scrim-back
    depends_on:
      - db
